TRAIN_DEFAULT_SETTINGS = {
    "utterances_path": "/home/usuaris/veussd/lucas.takanori/lt400/lt400.json",
    "random_seed": 1234,
    "max_epochs": 1,
    "use_weights_and_biases": False,
    "load_checkpoint" : False,
    "eval_and_save_best_model_every": 100,
    "training_augmentation_prob": 0,
    "evaluation_augmentation_prob": 0,
    "sample_rate": 16000,
    "whisper_flavour": "medium",
    "batch_size": 32,
    "num_workers": 4,
    "random_crop_secs": 30,
    "padding_type": "zero_pad",
    "asr_model": "whisper",
}